application: monoframe2
version: 27
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css))
  
- url: /.*
  script: main.py

error_handlers:
  - file: 404.html

  - error_code: over_quota
    file: over_quota.html

libraries:
- name: lxml
  version: "latest"